name: music_mental_health_analysis
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - typer
  - loguru
  - tqdm
  - imbalanced-learn
  - ipython
  - jupyterlab
  - matplotlib
  - missingno
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - scikit-posthocs
  - shap
  - ruff
  - pytest
  - ydata-profiling
  - pip:
    - kaggle
    - python-dotenv
    - mkdocs
    - -e .